apiVersion: apps/v1
kind: Deployment
metadata:
  name: NodeJs-app
  labels:
    app: NodeJs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: NodeJs-app
  template:
    metadata:
      labels:
        app: NodeJs-app
    spec:
      containers:
      - name: NodeJs-app
  image: 076226033208.dkr.ecr.ap-south-1.amazonaws.com/nodejs:f3e83f5dc44d538145052cf1a7891f082ae71c32
        ports:
        - containerPort: 3000
          #ismail
