apiVersion: apps/v1
kind: Deployment
metadata:
  name: NodeJs-app
  labels:
    app: NodeJs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: NodeJs-app
  template:
    metadata:
      labels:
        app: NodeJs-app
    spec:
      containers:
      - name: NodeJs-app
        image: attarismail/nodejsapp:1d9820c3af368532ba2bb17762049506bc83d37e
        ports:
        - containerPort: 3000
          #ismail
