name: NodeJs Application CICD pipeline

on:
  push:
    branches: [ "main" ]
jobs:
  Code-checkout:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - run: |
        ls -lrth
        

