name: node-js-app-cicd 
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v6.0.1

      - name: print-code
        run: |
          ls -l

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: code-checkout
        uses: actions/checkout@v6.0.1

      - name: set-up-nodeJS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 20
      - name: install dependencies
        run: |
          cd nodejs-sample-app
          npm install --only=production
      - run: |
          ls -l 
      

