name: node-js-app-cicd 
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v6.0.1

      - name: print-code
        run: |
          ls -l

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: code-checkout
        uses: actions/checkout@v6.0.1

      - name: set-up-nodeJS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 20
      - name: install dependencies
        run: |
          cd nodejs-sample-app
          npm init -y
          npm install 
          ls -l 

      - name: sonarqube scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        with:
          args:
            -Dproject.settings=nodejs-sample-app/sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: sonar qwality gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        id: sonarqube-quality-gate-check
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


      - name: upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: node-artifact
          path: nodejs-sample-app/package*.json


  Build-and-push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: code-checkout
        uses: actions/checkout@v6.0.1
      - name: dowload the artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: node-artifact
          path: nodejs-sample-app/
      - name: login to dockerhub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: push image to dockerhub
        uses: docker/build-push-action@v6
        with:
          context: nodejs-sample-app/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejsapp:${{ github.sha }}

  update-deployment-files:
    runs-on: ubuntu-latest
    needs: Build-and-push-image
    permissions:
      contents: write
    steps:
     - name: code-checkout
       uses: actions/checkout@v6.0.1
       with:
        token: ${{ secrets.GITHUB_TOKEN }}

       
     - run: |
        cd nodejs-sample-app-manifest
        sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/nodejsapp:${{ github.sha }}|" deployment.yaml   
        git config user.name "ismail"
        git config user.email "ismailattar@gmail.com"
        git add deployment.yaml
        git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
        git push origin main
        git fetch origin
        git checkout argocd
        git push origin argocd
      



