name: node-js-app-cicd 
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v6.0.1

      - name: print-code
        run: |
          ls -l

  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: code-checkout
        uses: actions/checkout@v6.0.1

      - name: set-up-nodeJS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 20
      - name: install dependencies
        run: |
          cd nodejs-sample-app
          npm install --only=production
          ls -l 

      - name: sonarqube scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        with:
          args:
            -Dproject.settings=nodejs-sample-app/sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: sonar qwality gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        id: sonarqube-quality-gate-check
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      