name: node-js-app-cicd 
on: push
jobs:
  checkout:
    runs-on: ubuntu
    steps:
      - name: code-checkout
        uses: actions/checkout@v6.0.1

      - name: print-code
        run: |
          ls -l